[package]
name = "example_pytorch_extension"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"

[lib]
crate-type=["cdylib"]

[dependencies]
flash_powder = {workspace=true, features=["cuda" ]}
torch_stable  = {workspace=true, features=["cuda" ]}
anyhow  = {workspace=true }


# This is only here because otherwise 'cargo t' complains with a linker error, it's not actually necessary to build the
# extension.
[build-dependencies]
torch_stable  = {workspace=true, features=["cuda" ]}


[lints]
workspace = true
